version: "3.3"

services:
    
  db:
    container_name: sistema_de_notas_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_sistema
    ports:
      - "5441:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./database/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    

  app:
    container_name: sistema_de_notas_app
    build: ./app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    depends_on:
      - db
    restart: always

volumes:
  database:
    driver: local

networks:
  default:
    external:
      name: local-net





  

